version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luxuriapure_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

  web:
    image: nginx:alpine
    container_name: luxuriapure_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app